### ISSUE TITLE
Manix Crashes on Cache building

### ISSUE THREAD

**Issue by HexSleeves** [mlvzk/manix#31]
Running manix straight from an install produces the following error:

```
Building Nixpkgs comments cache...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/comments_docsource.rs:178:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Havent been able to get around this

**Comment by hmajid2301** [comment]
I am suffering the same issue!

**Comment by axelkar** [comment]
This seems to be caused by https://github.com/NixOS/nixpkgs/commit/271eb0299503892944986eb381b79ec09ea2f2a4

https://github.com/NixOS/nixpkgs/tree/271eb0299503892944986eb381b79ec09ea2f2a4/pkgs/test/nixpkgs-check-by-name/tests/symlink-invalid/pkgs/by-name/fo/foo contains an invalid symlink

**Comment by izelnakri** [comment]
I just had the same issue after `nix profile install manix` on my machine(which is NOT NixOS). This essentially makes this cli/project useless currently thus would appreciate your attention @mlvzk :

```bash
$ uname -a
Linux x1-carbon 6.5.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 13 Sep 2023 08:37:40 +0000 x86_64 GNU/Linux

$ RUST_BACKTRACE=1 manix fetchurl
Building Nixpkgs comments cache...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/comments_docsource.rs:178:65
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   4: rayon::iter::plumbing::Folder::consume_iter
   5: rayon::iter::plumbing::bridge_producer_consumer::helper
   6: rayon_core::registry::in_worker
   7: rayon::iter::plumbing::bridge_producer_consumer::helper
   8: rayon_core::registry::in_worker
   9: rayon::iter::plumbing::bridge_producer_consumer::helper
  10: rayon_core::job::StackJob<L,F,R>::run_inline
  11: rayon_core::registry::in_worker
  12: rayon::iter::plumbing::bridge_producer_consumer::helper
  13: rayon_core::registry::in_worker
  14: rayon::iter::plumbing::bridge_producer_consumer::helper
  15: rayon_core::registry::in_worker
  16: rayon::iter::plumbing::bridge_producer_consumer::helper
  17: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  18: rayon_core::registry::WorkerThread::execute
  19: rayon_core::registry::WorkerThread::wait_until_cold
  20: rayon_core::registry::in_worker
  21: rayon::iter::plumbing::bridge_producer_consumer::helper
  22: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  23: rayon_core::registry::WorkerThread::wait_until_cold
  24: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by HexSleeves** [comment]
The last commit was 2 years ago. I just think it's dead at this point

**Comment by evelant** [comment]
It seems the original maintainer of this project is no longer active here or at all on github. Maybe we can point nixpkgs to a working fork if anyone is willing to maintain it?

**Comment by waalge** [comment]
@evelant I'm happy to try

**Comment by HexSleeves** [comment]
If anyone is still around, I forked the repo and updated it to a working state.

https://github.com/lecoqjacob/manix

**Comment by ParetoOptimalDev** [comment]
@lecoqjacob Perhaps you can create a PR on nixpkgs to change nixpkgs to use your working fork?

**Comment by HexSleeves** [comment]
> @lecoqjacob Perhaps you can create a PR on nixpkgs to change nixpkgs to use your working fork?

Yea I already have a PR up to switch maintainers! Should be good in a few days

**Comment by Artturin** [comment]
@lecoqjacob @waalge It's possible to filter all the broken stuff out in `find_nix_files` https://github.com/nix-community/nixpkgs-lint/blob/master/src/find.rs

**Comment by HexSleeves** [comment]
> @lecoqjacob @waalge It's possible to filter all the broken stuff out in `find_nix_files` https://github.com/nix-community/nixpkgs-lint/blob/master/src/find.rs

Oh this is a good find! I'll need to upstream this in my fork

**Comment by IogaMaster** [comment]
@ParetoOptimalDev We have now done this.
https://github.com/nix-community/manix

Working on updating the nixpkgs version
